export interface StyleData {
  id: number;
  nameCN: string;
  nameEN: string;
  bgColor: string;
  cardBg: string;
  textColor: string;
  accentColor: string;
  palette: string[];
  fontFamily: string;
  borderStyle: string;
  borderRadius: number;
  boxShadow: string;
  tags: string[];
  description: string;
}

export const STYLES: StyleData[] = [
  {
    id: 1,
    nameCN: "新粗野主义",
    nameEN: "Neo-Brutalism",
    bgColor: "#f5f3ee",
    cardBg: "#fff",
    textColor: "#111",
    accentColor: "#111",
    palette: ["#f5f3ee", "#fff", "#111", "#d4d0c8", "#555"],
    fontFamily: "DM Mono",
    borderStyle: "3px solid #111",
    borderRadius: 0,
    boxShadow: "6px 6px 0 #111",
    tags: ["粗黑边框", "点阵背景", "无圆角", "大写等宽"],
    description: "粗黑边框+点阵纹理+硬阴影，实验性粗粝视觉",
  },
  {
    id: 2,
    nameCN: "瑞士风格",
    nameEN: "Swiss Style",
    bgColor: "#fafaf9",
    cardBg: "#fafaf9",
    textColor: "#1a1a1a",
    accentColor: "#1a1a1a",
    palette: ["#fafaf9", "#1a1a1a", "#6b7280", "#e5e7eb"],
    fontFamily: "Inter",
    borderStyle: "1px solid #e5e7eb",
    borderRadius: 0,
    boxShadow: "none",
    tags: ["12列网格", "900字重", "非对称布局", "四色系统"],
    description: "12列CSS Grid + 900超粗标题 + 克制四色系统",
  },
  {
    id: 3,
    nameCN: "日系编辑美学",
    nameEN: "Japanese Editorial",
    bgColor: "#f1f0ea",
    cardBg: "#faf9f4",
    textColor: "#2c2b28",
    accentColor: "#dfff00",
    palette: ["#f1f0ea", "#faf9f4", "#2c2b28", "#dfff00", "#d4d3cc"],
    fontFamily: "Noto Sans SC",
    borderStyle: "1px solid #d4d3cc",
    borderRadius: 0,
    boxShadow: "none",
    tags: ["暖调纸色", "荧光黄下划线", "低对比分割", "中日文混排"],
    description: "暖调纸色底+荧光黄装饰+柔和分割线，杂志内页温度感",
  },
  {
    id: 4,
    nameCN: "终端/CLI 审美",
    nameEN: "Terminal Aesthetic",
    bgColor: "#0d0f0e",
    cardBg: "#0d0f0e",
    textColor: "#c5d0c0",
    accentColor: "#dfff00",
    palette: ["#0d0f0e", "#c5d0c0", "#dfff00", "#2454ff", "#4ec97a"],
    fontFamily: "DM Mono",
    borderStyle: "1px solid #2a302c",
    borderRadius: 0,
    boxShadow: "none",
    tags: ["绿色脉冲", "等宽全文本", "冷工业配色", "命令行提示符"],
    description: "黑底绿字+DM Mono全文本+命令行$提示符+状态脉冲圆点",
  },
  {
    id: 5,
    nameCN: "玻璃拟态",
    nameEN: "Glassmorphism",
    bgColor: "linear-gradient(135deg, #0a0e27, #141a3a)",
    cardBg: "rgba(255,255,255,0.06)",
    textColor: "#e8eaf0",
    accentColor: "#dfff00",
    palette: ["#0a0e27", "#141a3a", "#dfff00", "#2454ff", "#e8eaf0"],
    fontFamily: "Inter",
    borderStyle: "1px solid rgba(255,255,255,0.1)",
    borderRadius: 0,
    boxShadow: "none",
    tags: ["毛玻璃", "CRT扫描线", "酸黄×深蓝", "80s赛博"],
    description: "深色渐变+backdrop-filter模糊+扫描线覆盖+赛博配色",
  },
  {
    id: 6,
    nameCN: "体素美学",
    nameEN: "Voxel Aesthetic",
    bgColor: "#3d3d3d",
    cardBg: "#4a4a4a",
    textColor: "#c8c0a8",
    accentColor: "#7B8F3A",
    palette: ["#3d3d3d", "#7B8F3A", "#8B6B3D", "#6D6D6D", "#C4A87C"],
    fontFamily: "Press Start 2P",
    borderStyle: "2px solid #6d6d6d",
    borderRadius: 0,
    boxShadow: "inset 0 -4px 0 #2B2B2B, 4px 4px 0 #2B2B2B",
    tags: ["像素字体", "立体方块", "物品栏网格", "大地色谱"],
    description: "Press Start 2P像素字体+16px网格+立体凸起边框+游戏UI",
  },
  {
    id: 7,
    nameCN: "新拟物化",
    nameEN: "Neumorphism",
    bgColor: "#e0e5ec",
    cardBg: "#e0e5ec",
    textColor: "#3a4a5a",
    accentColor: "#6c8aaf",
    palette: ["#e0e5ec", "#3a4a5a", "#5a6575", "#8a95a5", "#c2c8d2"],
    fontFamily: "Inter",
    borderStyle: "none",
    borderRadius: 20,
    boxShadow: "8px 8px 16px #c2c8d2, -8px -8px 16px #fefeff",
    tags: ["对向阴影", "同色背景", "20px圆角", "inset凹陷"],
    description: "卡片与背景同色+对向box-shadow浮雕效果+inset按下态",
  },
  {
    id: 8,
    nameCN: "复古 Win95",
    nameEN: "Retro Win95",
    bgColor: "#008080",
    cardBg: "#c0c0c0",
    textColor: "#000",
    accentColor: "#000080",
    palette: ["#008080", "#c0c0c0", "#000080", "#dfdfdf", "#000"],
    fontFamily: "MS Sans Serif",
    borderStyle: "outset 2px #dfdfdf",
    borderRadius: 0,
    boxShadow: "inset 1px 1px 0 #fff, 1px 1px 0 #808080",
    tags: ["3D凸起边框", "青绿桌面", "渐变标题栏", "虚线聚焦框"],
    description: "#008080青绿桌面+3D凸起/凹陷边框+MS Sans Serif",
  },
  {
    id: 9,
    nameCN: "有机自然",
    nameEN: "Biophilic Design",
    bgColor: "#f3f0e8",
    cardBg: "#fdfbf5",
    textColor: "#3a4035",
    accentColor: "#6b8a5e",
    palette: ["#f3f0e8", "#fdfbf5", "#6b8a5e", "#4a6a3e", "#8a9a7a"],
    fontFamily: "Inter",
    borderStyle: "none",
    borderRadius: 16,
    boxShadow: "0 4px 20px rgba(0,0,0,0.06)",
    tags: ["大地色系", "鼠尾草绿", "diffuse阴影", "大圆角"],
    description: "奶油米底+鼠尾草绿+漫反射阴影+充裕留白呼吸感",
  },
  {
    id: 10,
    nameCN: "3D超写实",
    nameEN: "3D Hyperrealism",
    bgColor: "#1a1a2e",
    cardBg: "linear-gradient(135deg, rgba(255,255,255,0.1), rgba(255,255,255,0.05))",
    textColor: "#e8e8f0",
    accentColor: "#6c63ff",
    palette: ["#1a1a2e", "#2a2a4e", "#6c63ff", "#e8e8f0", "#0a0a1a"],
    fontFamily: "Inter",
    borderStyle: "1px solid rgba(255,255,255,0.1)",
    borderRadius: 12,
    boxShadow: "0 20px 60px rgba(0,0,0,0.5), 0 0 0 1px rgba(255,255,255,0.05)",
    tags: ["perspective透视", "translateZ深度", "真实材质", "多光源阴影"],
    description: "perspective+translateZ+多层阴影+逼真材质模拟",
  },
  {
    id: 11,
    nameCN: "鲜艳块状",
    nameEN: "Vibrant & Block",
    bgColor: "#fff",
    cardBg: "#fff",
    textColor: "#111",
    accentColor: "#ff6b6b",
    palette: ["#fff", "#ff6b6b", "#ffd93d", "#111", "#ffe0e0"],
    fontFamily: "Inter",
    borderStyle: "3px solid #111",
    borderRadius: 0,
    boxShadow: "4px 8px 0 #111",
    tags: ["高饱和撞色", "粗黑边框", "硬阴影", "零圆角"],
    description: "红黄高饱和撞色+3px粗黑边框+硬阴影偏移，强烈视觉冲击",
  },
  {
    id: 12,
    nameCN: "OLED 暗黑",
    nameEN: "Dark Mode OLED",
    bgColor: "#000",
    cardBg: "#0a0a0a",
    textColor: "#fff",
    accentColor: "#fff",
    palette: ["#000", "#0a0a0a", "#fff", "#1a1a1a", "#888"],
    fontFamily: "Inter",
    borderStyle: "1px solid #1a1a1a",
    borderRadius: 8,
    boxShadow: "none",
    tags: ["纯黑底色", "极暗卡片", "高对比白字", "OLED节能"],
    description: "纯黑#000底色+极暗卡片+高对比白字，OLED像素级黑色",
  },
  {
    id: 13,
    nameCN: "无障碍伦理",
    nameEN: "Accessible & Ethical",
    bgColor: "#fff",
    cardBg: "#fff",
    textColor: "#000",
    accentColor: "#0052cc",
    palette: ["#fff", "#000", "#0052cc", "#eee", "#666"],
    fontFamily: "Atkinson Hyperlegible",
    borderStyle: "2px solid #000",
    borderRadius: 4,
    boxShadow: "none",
    tags: ["WCAG AAA", "4.5:1对比度", "清晰焦点框", "语义HTML"],
    description: "严格WCAG标准+高可读字体+可见焦点指示器+44px触摸目标",
  },
  {
    id: 14,
    nameCN: "粘土风",
    nameEN: "Claymorphism",
    bgColor: "#f0c9a0",
    cardBg: "#f0c9a0",
    textColor: "#5a3a2a",
    accentColor: "#c8784a",
    palette: ["#f0c9a0", "#e8b890", "#d4a070", "#c8784a", "#ffe8d0"],
    fontFamily: "Inter",
    borderStyle: "none",
    borderRadius: 24,
    boxShadow: "8px 8px 16px rgba(180,130,100,0.3), -8px -8px 16px rgba(255,230,210,0.5)",
    tags: ["柔软3D块", "大圆角24px", "泥土色调", "playful"],
    description: "同色背景+对向柔和阴影+24px大圆角，俏皮玩具质感",
  },
  {
    id: 15,
    nameCN: "极光界面",
    nameEN: "Aurora UI",
    bgColor: "#0a0a1a",
    cardBg: "rgba(255,255,255,0.04)",
    textColor: "#e0e0f0",
    accentColor: "#0d9488",
    palette: ["#0a0a1a", "#1a0a3e", "#0d9488", "#6366f1", "#f472b6"],
    fontFamily: "Inter",
    borderStyle: "1px solid rgba(255,255,255,0.08)",
    borderRadius: 12,
    boxShadow: "none",
    tags: ["radial光斑", "蓝绿紫交织", "毛玻璃卡片", "北极光色彩"],
    description: "深色底+多层radial-gradient光斑+毛玻璃，模拟北极光流动",
  },
  {
    id: 16,
    nameCN: "复古未来",
    nameEN: "Retro-Futurism",
    bgColor: "#1a0a2e",
    cardBg: "rgba(40,20,60,0.8)",
    textColor: "#e0d0f0",
    accentColor: "#ff6b9d",
    palette: ["#1a0a2e", "#2a1a4e", "#ff6b9d", "#d0b0f0", "#0a0a2e"],
    fontFamily: "Inter",
    borderStyle: "1px solid rgba(255,107,157,0.3)",
    borderRadius: 8,
    boxShadow: "0 0 20px rgba(255,107,157,0.2)",
    tags: ["太空深紫", "霓虹粉", "发光边框", "80s科幻"],
    description: "太空深紫背景+霓虹粉发光边框+半透明紫色卡片，温暖科技怀旧",
  },
  {
    id: 17,
    nameCN: "扁平设计",
    nameEN: "Flat Design",
    bgColor: "#f8f9fa",
    cardBg: "#fff",
    textColor: "#2c3e50",
    accentColor: "#3490dc",
    palette: ["#f8f9fa", "#fff", "#3490dc", "#2c3e50", "#e9ecef"],
    fontFamily: "Inter",
    borderStyle: "1px solid #e9ecef",
    borderRadius: 4,
    boxShadow: "none",
    tags: ["零阴影", "纯色卡片", "鲜明品牌色", "纯二维"],
    description: "无阴影无渐变无纹理的纯平面，鲜明品牌色+清晰网格",
  },
  {
    id: 18,
    nameCN: "液态玻璃",
    nameEN: "Liquid Glass",
    bgColor: "linear-gradient(135deg, #0a0a1a, #1a0a2e, #0a0a1a)",
    cardBg: "rgba(255,255,255,0.03)",
    textColor: "#e8e8f0",
    accentColor: "#6366f1",
    palette: ["#0a0a1a", "#1a0a2e", "#6366f1", "#e8e8f0", "rgba(255,255,255,0.05)"],
    fontFamily: "Inter",
    borderStyle: "1px solid rgba(255,255,255,0.06)",
    borderRadius: 16,
    boxShadow: "none",
    tags: ["blur 20px", "微光边框", "液体表面张力", "SaaS质感"],
    description: "超强模糊blur(20px)+微光边框+16px圆角，高级SaaS质感",
  },
  {
    id: 19,
    nameCN: "动效驱动",
    nameEN: "Motion-Driven",
    bgColor: "#0a0a0a",
    cardBg: "#111",
    textColor: "#fff",
    accentColor: "#ff4444",
    palette: ["#0a0a0a", "#111", "#ff4444", "#fff", "#333"],
    fontFamily: "Inter",
    borderStyle: "1px solid #222",
    borderRadius: 8,
    boxShadow: "none",
    tags: ["弹簧缓动", "hover缩放旋转", "scroll触发", "动效即设计"],
    description: "cubic-bezier弹性缓动+悬浮缩放旋转+滚动渐入，动效为主体语言",
  },
  {
    id: 20,
    nameCN: "微交互",
    nameEN: "Micro-interactions",
    bgColor: "#fafafa",
    cardBg: "#fff",
    textColor: "#333",
    accentColor: "#0066ff",
    palette: ["#fafafa", "#fff", "#0066ff", "#333", "#eee"],
    fontFamily: "Inter",
    borderStyle: "1px solid #eee",
    borderRadius: 12,
    boxShadow: "0 2px 4px rgba(0,0,0,0.04)",
    tags: ["点击缩放", "弹性过渡", "渐进阴影", "像素回应"],
    description: "按钮active scale(0.95)+悬浮渐进阴影+hover弹性抬升",
  },
  {
    id: 21,
    nameCN: "包容性设计",
    nameEN: "Inclusive Design",
    bgColor: "#fff",
    cardBg: "#fff",
    textColor: "#000",
    accentColor: "#000",
    palette: ["#fff", "#000", "#eee", "#666", "#f5f5f5"],
    fontFamily: "Inter",
    borderStyle: "2px solid #000",
    borderRadius: 4,
    boxShadow: "none",
    tags: ["2px粗边框", "44px触摸目标", "可见焦点", "高对比"],
    description: "高对比黑边框+大号触摸目标+键盘可见焦点+语义化层级",
  },
  {
    id: 22,
    nameCN: "零界面",
    nameEN: "Zero Interface",
    bgColor: "#fff",
    cardBg: "transparent",
    textColor: "#1a1a1a",
    accentColor: "#ccc",
    palette: ["#fff", "#1a1a1a", "#ccc", "#888", "#fafafa"],
    fontFamily: "Inter",
    borderStyle: "none",
    borderRadius: 0,
    boxShadow: "none",
    tags: ["透明卡片", "无边框", "无hover", "纯留白层级"],
    description: "无卡片边框+无背景+无分割线，内容漂浮，仅靠留白和字号分层",
  },
  {
    id: 23,
    nameCN: "柔和UI进化",
    nameEN: "Soft UI Evolution",
    bgColor: "#eef0f4",
    cardBg: "#fff",
    textColor: "#2c3e50",
    accentColor: "#6382dc",
    palette: ["#eef0f4", "#fff", "#6382dc", "#2c3e50", "#d0d5e0"],
    fontFamily: "Inter",
    borderStyle: "1px solid #e8eaf0",
    borderRadius: 14,
    boxShadow: "0 2px 12px rgba(0,0,0,0.06)",
    tags: ["多层阴影", "极浅蓝灰底", "蓝紫渐变按钮", "14px圆角"],
    description: "极浅蓝灰底+1px边框+多层阴影+蓝紫按钮，企业级柔和设计",
  },
  {
    id: 24,
    nameCN: "新粗野2.0",
    nameEN: "Neubrutalism",
    bgColor: "#fffaee",
    cardBg: "#fff",
    textColor: "#111",
    accentColor: "#ff6b6b",
    palette: ["#fffaee", "#ff6b6b", "#ffd93d", "#111", "#fff"],
    fontFamily: "Inter",
    borderStyle: "3px solid #000",
    borderRadius: 0,
    boxShadow: "4px 4px 0 #000",
    tags: ["暖色奶油底", "红黄撞色", "硬阴影", "Gen Z友好"],
    description: "暖色奶油底+红黄弹出色+硬阴影偏移，乐观版粗野主义",
  },
  {
    id: 25,
    nameCN: "便当盒网格",
    nameEN: "Bento Box Grid",
    bgColor: "#f5f5f7",
    cardBg: "#fff",
    textColor: "#1a1a1a",
    accentColor: "#0071e3",
    palette: ["#f5f5f7", "#fff", "#0071e3", "#1a1a1a", "#e8e8ed"],
    fontFamily: "Inter",
    borderStyle: "none",
    borderRadius: 18,
    boxShadow: "0 2px 8px rgba(0,0,0,0.04)",
    tags: ["不等大圆角卡片", "Apple灰调", "无边框", "胶囊按钮"],
    description: "Apple灰底+不等大圆角卡片+微弱阴影，日式便当盒排列",
  },
  {
    id: 26,
    nameCN: "Y2K 美学",
    nameEN: "Y2K Aesthetic",
    bgColor: "linear-gradient(135deg, #d1f7ff, #ffccde)",
    cardBg: "rgba(255,255,255,0.5)",
    textColor: "#2a2a5a",
    accentColor: "#ff69b4",
    palette: ["#d1f7ff", "#ffccde", "#ff69b4", "#2a2a5a", "#fff"],
    fontFamily: "Inter",
    borderStyle: "1px solid rgba(255,255,255,0.8)",
    borderRadius: 16,
    boxShadow: "0 4px 20px rgba(255,105,180,0.2)",
    tags: ["冰蓝渐变", "磨砂半透明", "hot pink", "千禧乐观"],
    description: "冰蓝→樱花粉渐变+磨砂卡片+hot pink辉光，千禧年科技乐观",
  },
  {
    id: 27,
    nameCN: "赛博朋克",
    nameEN: "Cyberpunk UI",
    bgColor: "#0a0a0a",
    cardBg: "#0a0a0a",
    textColor: "#e0e0e0",
    accentColor: "#ff00ff",
    palette: ["#0a0a0a", "#ff00ff", "#00ff88", "#000", "#333"],
    fontFamily: "DM Mono",
    borderStyle: "1px solid rgba(255,0,255,0.3)",
    borderRadius: 0,
    boxShadow: "0 0 10px rgba(255,0,255,0.3)",
    tags: ["霓虹品红", "亮绿", "发光边框", "高科技低生活"],
    description: "纯黑底+品红亮绿霓虹双色+发光边框+文字辉光+零圆角",
  },
  {
    id: 28,
    nameCN: "AI原生界面",
    nameEN: "AI-Native UI",
    bgColor: "#fafbff",
    cardBg: "#fff",
    textColor: "#1a1a2e",
    accentColor: "#667eea",
    palette: ["#fafbff", "#667eea", "#764ba2", "#fff", "#e8eaf6"],
    fontFamily: "Inter",
    borderStyle: "1px solid #e0e4f0",
    borderRadius: 12,
    boxShadow: "0 2px 12px rgba(102,126,234,0.1)",
    tags: ["蓝紫渐变", "流线型圆角", "对话气泡", "打字机光标"],
    description: "蓝紫渐变品牌色+流线型圆角卡片+AI智能感产品界面",
  },
  {
    id: 29,
    nameCN: "孟菲斯设计",
    nameEN: "Memphis Design",
    bgColor: "#fff5ee",
    cardBg: "#fff",
    textColor: "#2a2a3a",
    accentColor: "#ff6b6b",
    palette: ["#fff5ee", "#ff6b6b", "#4ecdc4", "#ffe66d", "#fff"],
    fontFamily: "Inter",
    borderStyle: "2px solid #4ecdc4",
    borderRadius: 20,
    boxShadow: "4px 4px 0 #4ecdc4",
    tags: ["几何色块", "波点锯齿", "三色撞色", "胶囊按钮"],
    description: "粉青黄三色撞色+彩色硬阴影+波点装饰+20px胶囊按钮",
  },
  {
    id: 30,
    nameCN: "蒸汽波",
    nameEN: "Vaporwave",
    bgColor: "linear-gradient(180deg, #0a0a2e, #1a0a3e)",
    cardBg: "rgba(20,10,40,0.8)",
    textColor: "#e8a0ff",
    accentColor: "#00ffff",
    palette: ["#0a0a2e", "#1a0a3e", "#ff00ff", "#00ffff", "#e8a0ff"],
    fontFamily: "Inter",
    borderStyle: "1px solid rgba(255,0,255,0.2)",
    borderRadius: 8,
    boxShadow: "0 0 15px rgba(255,0,255,0.2)",
    tags: ["深紫渐变", "霓虹粉紫", "青色辉光", "合成波美学"],
    description: "深紫渐变+霓虹粉紫文字+青色辉光+半透明层叠，迷幻合成波",
  },
  {
    id: 31,
    nameCN: "维度层叠",
    nameEN: "Dimensional Layering",
    bgColor: "#f0f0f5",
    cardBg: "#fff",
    textColor: "#2c3e50",
    accentColor: "#5b6abf",
    palette: ["#f0f0f5", "#fff", "#5b6abf", "#2c3e50", "#e0e0e8"],
    fontFamily: "Inter",
    borderStyle: "1px solid #eee",
    borderRadius: 10,
    boxShadow: "0 1px 2px rgba(0,0,0,0.04), 0 4px 8px rgba(0,0,0,0.04)",
    tags: ["递进阴影", "Z轴分层", "悬浮hover", "仪表盘布局"],
    description: "多层递进box-shadow+1px边框+悬浮抬升，仪表盘最佳方案",
  },
  {
    id: 32,
    nameCN: "极度极简",
    nameEN: "Exaggerated Minimalism",
    bgColor: "#fff",
    cardBg: "#fff",
    textColor: "#000",
    accentColor: "#000",
    palette: ["#fff", "#000", "#eee", "#f5f5f5", "#ccc"],
    fontFamily: "Inter",
    borderStyle: "none",
    borderRadius: 0,
    boxShadow: "none",
    tags: ["5rem标题", "900字重", "无hover", "留白即设计"],
    description: "超大5rem标题+900超粗字重+纯白背景+极致留白",
  },
  {
    id: 33,
    nameCN: "动态排版",
    nameEN: "Kinetic Typography",
    bgColor: "#000",
    cardBg: "#000",
    textColor: "#fff",
    accentColor: "#fff",
    palette: ["#000", "#fff", "#333", "#999", "#111"],
    fontFamily: "Inter",
    borderStyle: "none",
    borderRadius: 0,
    boxShadow: "none",
    tags: ["文字即Hero", "6rem+", "0.9行高", "黑白极端对比"],
    description: "文字即视觉主体—6rem+超大字体+900字重+紧凑行高+黑白极端对比",
  },
  {
    id: 34,
    nameCN: "视差叙事",
    nameEN: "Parallax Storytelling",
    bgColor: "linear-gradient(180deg, #f5f0e8, #e8ddd0, #f5f0e8)",
    cardBg: "rgba(255,255,255,0.7)",
    textColor: "#3a2a1a",
    accentColor: "#8b6914",
    palette: ["#f5f0e8", "#e8ddd0", "#3a2a1a", "#8b6914", "#fff"],
    fontFamily: "Inter",
    borderStyle: "1px solid rgba(0,0,0,0.05)",
    borderRadius: 8,
    boxShadow: "0 4px 30px rgba(0,0,0,0.08)",
    tags: ["多层渐变背景", "Z轴滚动", "半透明叠加", "故事书体验"],
    description: "多层暖色渐变+半透明卡片叠加+不同速度滚动，沉浸叙事",
  },
  {
    id: 35,
    nameCN: "瑞士现代2.0",
    nameEN: "Swiss Modernism 2.0",
    bgColor: "#fcfcfc",
    cardBg: "#fcfcfc",
    textColor: "#0a0a0a",
    accentColor: "#0a0a0a",
    palette: ["#fcfcfc", "#0a0a0a", "#666", "#e0e0e0", "#f0f0f0"],
    fontFamily: "Inter",
    borderStyle: "none",
    borderRadius: 0,
    boxShadow: "none",
    tags: ["2px顶部黑线", "4rem标题", "0.85行高", "零阴影零圆角"],
    description: "纯白底+仅2px黑色顶部线分割+超大标题+字体即唯一材料",
  },
  {
    id: 36,
    nameCN: "科幻HUD",
    nameEN: "HUD / Sci-Fi FUI",
    bgColor: "#001020",
    cardBg: "rgba(0,20,40,0.8)",
    textColor: "#88ccff",
    accentColor: "#00aaff",
    palette: ["#001020", "#00aaff", "#88ccff", "#003050", "#002040"],
    fontFamily: "DM Mono",
    borderStyle: "1px solid rgba(0,170,255,0.3)",
    borderRadius: 0,
    boxShadow: "0 0 10px rgba(0,170,255,0.2)",
    tags: ["发光青色边框", "深空蓝底", "等宽字体", "扫描线"],
    description: "深空蓝底+发光青色边框+辉光阴影+等宽字体，全息投影界面",
  },
  {
    id: 37,
    nameCN: "便当网格2.0",
    nameEN: "Bento Grids 2.0",
    bgColor: "#f2f2f7",
    cardBg: "#fff",
    textColor: "#1a1a1a",
    accentColor: "#ff3b30",
    palette: ["#f2f2f7", "#fff", "#ff3b30", "#1a1a1a", "#e5e5ea"],
    fontFamily: "Inter",
    borderStyle: "none",
    borderRadius: 20,
    boxShadow: "none",
    tags: ["暖灰底色", "红色点缀", "20px大圆角", "不等大拼接"],
    description: "暖灰底色+#ff3b30红色点缀+20px大圆角，比Apple Bento更有温度",
  },
  {
    id: 38,
    nameCN: "空间计算",
    nameEN: "Spatial UI (VisionOS)",
    bgColor: "linear-gradient(135deg, #0a0a2e, #1a1a4e, #0a0a2e)",
    cardBg: "rgba(255,255,255,0.08)",
    textColor: "#e8e8f0",
    accentColor: "#8b8cf0",
    palette: ["#0a0a2e", "#1a1a4e", "#8b8cf0", "#e8e8f0", "rgba(255,255,255,0.1)"],
    fontFamily: "Inter",
    borderStyle: "1px solid rgba(255,255,255,0.08)",
    borderRadius: 22,
    boxShadow: "none",
    tags: ["blur 20px", "22px圆角", "微光玻璃轮廓", "深空背景"],
    description: "强模糊blur(20px)+22px超大圆角+微光边框+空间悬浮感",
  },
  {
    id: 39,
    nameCN: "电子墨水",
    nameEN: "E-Ink / Paper",
    bgColor: "#faf8f0",
    cardBg: "#faf8f0",
    textColor: "#2a2a20",
    accentColor: "#5a5a4a",
    palette: ["#faf8f0", "#2a2a20", "#5a5a4a", "#ddd8c8", "#f0ede0"],
    fontFamily: "Georgia",
    borderStyle: "none",
    borderRadius: 0,
    boxShadow: "none",
    tags: ["暖白纸色", "Georgia衬线", "1.8行高", "零阴影"],
    description: "暖白纸色+Georgia衬线字体+16px/1.8行高+底部细线分割，电子纸阅读体验",
  },
  {
    id: 40,
    nameCN: "Z世代混沌",
    nameEN: "Gen Z Chaos / Maximalism",
    bgColor: "#fff",
    cardBg: "#ff6b35",
    textColor: "#fff",
    accentColor: "#ffd700",
    palette: ["#000", "#ffd700", "#ff6b35", "#fff", "#111"],
    fontFamily: "Inter",
    borderStyle: "2px solid #000",
    borderRadius: 30,
    boxShadow: "3px 3px 0 #ff6b35",
    tags: ["黑+亮黄", "橙红撞色", "粗黑边框", "30px胶囊"],
    description: "黑色header+亮黄+橙红撞色+粗黑边框+大胶囊按钮，有序混沌",
  },
  {
    id: 41,
    nameCN: "仿生有机2.0",
    nameEN: "Biomimetic / Organic 2.0",
    bgColor: "linear-gradient(180deg, #e8f0e8, #d0ddd0)",
    cardBg: "rgba(255,255,255,0.5)",
    textColor: "#2a3a2a",
    accentColor: "#2a4a2a",
    palette: ["#e8f0e8", "#d0ddd0", "#2a4a2a", "#4a6a4a", "#fff"],
    fontFamily: "Inter",
    borderStyle: "1px solid rgba(255,255,255,0.6)",
    borderRadius: 20,
    boxShadow: "0 4px 16px rgba(0,0,0,0.05)",
    tags: ["半透明层叠", "绿灰渐变", "20px有机圆角", "深绿点缀"],
    description: "半透明白色卡片+绿灰渐变背景+20px有机圆角+深绿植物色调",
  },
  {
    id: 42,
    nameCN: "反精致粗糙",
    nameEN: "Anti-Polish / Raw",
    bgColor: "#fff",
    cardBg: "#fff",
    textColor: "#111",
    accentColor: "#111",
    palette: ["#fff", "#111", "#999", "#eee", "#555"],
    fontFamily: "DM Mono",
    borderStyle: "1px dashed #999",
    borderRadius: 0,
    boxShadow: "none",
    tags: ["虚线边框", "等宽字体", "无阴影", "无圆角"],
    description: "虚线边框+DM Mono等宽+零圆角零阴影+拒绝精修，拥抱原始",
  },
  {
    id: 43,
    nameCN: "触觉数字",
    nameEN: "Tactile Digital",
    bgColor: "#f8f5f0",
    cardBg: "#fff",
    textColor: "#3a2a1a",
    accentColor: "#6a4a2a",
    palette: ["#f8f5f0", "#fff", "#6a4a2a", "#3a2a1a", "#e8e0d5"],
    fontFamily: "Inter",
    borderStyle: "none",
    borderRadius: 10,
    boxShadow: "0 2px 0 rgba(0,0,0,0.1)",
    tags: ["底部2px阴影", "scale(0.98)按压", "棉纸底色", "深棕按钮"],
    description: "底部2px阴影模拟厚度+active scale(0.98)按压+温暖棉纸质感",
  },
  {
    id: 44,
    nameCN: "自然精粹",
    nameEN: "Nature Distilled",
    bgColor: "#f5f2eb",
    cardBg: "#faf8f4",
    textColor: "#3a3530",
    accentColor: "#5a6a4a",
    palette: ["#f5f2eb", "#faf8f4", "#5a6a4a", "#3a3530", "#e8e0d5"],
    fontFamily: "Inter",
    borderStyle: "none",
    borderRadius: 6,
    boxShadow: "0 1px 3px rgba(0,0,0,0.03)",
    tags: ["奶油米底", "森林绿header", "极弱阴影", "6px圆角"],
    description: "奶油米底色+森林绿点缀+极弱阴影+6px精致圆角，提炼自然精华",
  },
  {
    id: 45,
    nameCN: "光标交互",
    nameEN: "Interactive Cursor",
    bgColor: "#1a1a2e",
    cardBg: "#1e1e35",
    textColor: "#c8c8e0",
    accentColor: "#6c6cff",
    palette: ["#1a1a2e", "#1e1e35", "#6c6cff", "#c8c8e0", "#0a0a20"],
    fontFamily: "DM Mono",
    borderStyle: "1px solid rgba(255,255,255,0.05)",
    borderRadius: 0,
    boxShadow: "0 0 20px rgba(108,108,255,0.1)",
    tags: ["crosshair光标", "发光微辉", "深紫科技蓝", "鼠标响应"],
    description: "crosshair十字准星光标+发光卡片微辉+深紫科技蓝背景",
  },
  {
    id: 46,
    nameCN: "语音优先",
    nameEN: "Voice-First Multimodal",
    bgColor: "#0a0a1a",
    cardBg: "rgba(255,255,255,0.04)",
    textColor: "#ccd0ee",
    accentColor: "#8888ff",
    palette: ["#0a0a1a", "#ccd0ee", "#8888ff", "#1a1a3a", "rgba(255,255,255,0.06)"],
    fontFamily: "Inter",
    borderStyle: "1px solid rgba(255,255,255,0.06)",
    borderRadius: 16,
    boxShadow: "none",
    tags: ["深蓝黑底", "柔和蓝紫文字", "16px圆角", "超大触摸目标"],
    description: "深蓝黑底+柔和蓝紫文字+16px亲和圆角+声波纹扩散意象",
  },
  {
    id: 47,
    nameCN: "3D产品展示",
    nameEN: "3D Product Preview",
    bgColor: "#fafafa",
    cardBg: "#fff",
    textColor: "#1a1a1a",
    accentColor: "#000",
    palette: ["#fafafa", "#fff", "#000", "#1a1a1a", "#eee"],
    fontFamily: "Inter",
    borderStyle: "none",
    borderRadius: 12,
    boxShadow: "0 8px 30px rgba(0,0,0,0.12)",
    tags: ["8px深阴影", "悬浮感", "12px圆角", "摄影棚白底"],
    description: "极简白底+8px深阴影悬浮感+12px精致圆角，Apple产品展示风格",
  },
  {
    id: 48,
    nameCN: "渐变网格",
    nameEN: "Gradient Mesh / Aurora Evolved",
    bgColor: "#0a0a1a",
    cardBg: "rgba(255,255,255,0.04)",
    textColor: "#e0e0f0",
    accentColor: "#f472b6",
    palette: ["#0a0a1a", "#f472b6", "#00ffff", "#6366f1", "rgba(255,255,255,0.06)"],
    fontFamily: "Inter",
    borderStyle: "1px solid rgba(255,255,255,0.06)",
    borderRadius: 12,
    boxShadow: "none",
    tags: ["多层radial光斑", "粉红+青色", "blur 8px", "多色多层网格"],
    description: "多层radial-gradient粉红+青色光斑叠加+半透明玻璃卡片，Aurora进化版",
  },
  {
    id: 49,
    nameCN: "色差RGB分裂",
    nameEN: "Chromatic Aberration / RGB Split",
    bgColor: "#000",
    cardBg: "#000",
    textColor: "#fff",
    accentColor: "#ff0000",
    palette: ["#000", "#ff0000", "#00ff00", "#0000ff", "#fff"],
    fontFamily: "DM Mono",
    borderStyle: "none",
    borderRadius: 0,
    boxShadow: "1px 0 #ff0000, 2px 0 #00ff00, 3px 0 #0000ff",
    tags: ["三色分离边框", "RGB文字色散", "纯黑底", "故障艺术"],
    description: "三色分离边框+RGB色散text-shadow+纯黑底+故障艺术效果",
  },
  {
    id: 50,
    nameCN: "复古胶片",
    nameEN: "Vintage Analog / Retro Film",
    bgColor: "#f5e8d0",
    cardBg: "#faf0dd",
    textColor: "#3a2a10",
    accentColor: "#8b6914",
    palette: ["#f5e8d0", "#faf0dd", "#3a2a10", "#8b6914", "#e0d5c0"],
    fontFamily: "Georgia",
    borderStyle: "none",
    borderRadius: 4,
    boxShadow: "0 2px 8px rgba(100,70,20,0.15)",
    tags: ["暖黄纸色", "Georgia衬线", "胶片颗粒", "棕色柔和阴影"],
    description: "暖黄纸色+Georgia衬线+16px/1.7行高+棕色柔和阴影，老照片怀旧感",
  },
];

export const TOTAL_STYLES = STYLES.length;
